version: "3"
services:
  bot-1:
    restart: "no"
    shm_size: 800m
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      - KUBERNETES_SERVICE_HOST=True
    ports:
      - "3000:3000"
      - "8000:8000"